version: "3"
services:
  postgresql:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: thecakeisalie
      POSTGRES_DB: serverless-db
    volumes:
      - './temp/postgresql:/var/lib/postgresql/data'

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - './temp/mongo:/data/db'
